FROM python:3.9-slim AS compile-image
COPY pip-requirements.txt .
RUN pip install --user --no-cache-dir --upgrade -r pip-requirements.txt

FROM python:3.9-slim AS build-image
COPY --from=compile-image /root/.local /root/.local
WORKDIR /app
COPY ./src ./src
# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80"]